import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menubar from "@/components/Menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <Menubar />
        <div className="flex-col w-full">
          <div className={inter.className}>
            {children}
            {/* Here you can Import or Create Common Footer */}
          </div>
        </div>
      </body>
    </html>
  );
}
